# -*- coding: utf-8 -*-
"""How to Display an Image using OpenCV.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qyQkBMBAnJhVgg8YIlzHd3MrUJ01w-0I
"""

import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt

!pip install opencv-python



"""# Loading an Image using"""

img = cv.imread('rgb.jpeg')
img = cv.cvtColor(img, cv.COLOR_BGR2RGB)
cv.imshow("Image",img)
cv.waitKey(0)

img = cv.imread('Transition.jpg')
img = cv.cvtColor(img, cv.COLOR_BGR2RGB)
cv.imshow("Image",img)
cv.waitKey(0)





"""#  DIsplaying 3 Frames on RGB"""

img = cv.imread('rgb.jpeg')
img = cv.cvtColor(img, cv.COLOR_BGR2RGB)

r = img[ :  , : , 0 ]  # - Red
g = img[ :  , : , 1 ]  # - Green
b = img[ :  , : , 2 ]  # - Blue


cv.imshow("Frame",r)
cv.waitKey(0)

cv.imshow("Frame",g)
cv.waitKey(0)

cv.imshow("Frame",b)
cv.waitKey(0)





