# -*- coding: utf-8 -*-
"""RGB IS DIFFRENT DROM BGR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AaQwL0rVD5Y_BomfqiQo7gu9zVi_rOWp
"""

import cv2 as cv

import numpy as np

import matplotlib.pyplot as plt

"""# Loading the image"""

img=cv.imread('/content/rgb.jpeg')


plt.imshow(img)



"""# CONVERT BGR TO RGB"""

img=cv.cvtColor(img,cv.COLOR_BGR2RGB)

plt.imshow(img)

img=cv.cvtColor(img,cv.COLOR_RGB2BGR)

plt.imshow(img)

img=cv.cvtColor(img,cv.COLOR_BGR2RGB)

plt.imshow(img)

img=cv.cvtColor(img,cv.COLOR_BGR2RGB)

plt.imshow(img)

img=cv.cvtColor(img,cv.COLOR_BGR2RGB)

plt.imshow(img)

img = cv.imread('Transition.jpg')

plt.imshow(img)

img = cv.cvtColor(img, cv.COLOR_RGB2BGR)

plt.imshow(img)