# -*- coding: utf-8 -*-
"""How to create an coloured images from scratch.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ULAidUsPPrsGcwH9LxTa9tAqM_QI7kc6
"""



import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt



"""# R G B

CREATING RED IMAGE
"""

arr = np.array([[[ 255 , 0 , 0 ] , [ 255 , 0 , 0 ] ,[ 255 , 0 , 0 ]],
                [[ 255 , 0 , 0 ] , [ 255 , 0 , 0 ] ,[ 255 , 0 , 0 ]],
                [[ 255 , 0 , 0 ] , [ 255 , 0 , 0 ] ,[ 255 , 0 , 0 ]]])

plt.imshow(arr)





"""# CREATING GREEN IMAGE"""

arr = np.array([[[ 0, 255 , 0  ] , [ 0, 255 , 0 ] ,[ 0, 255 , 0 ]],
                [[ 0, 255 , 0  ] , [ 0, 255 , 0 ] ,[ 0, 255 , 0 ]],
                [[ 0, 255 , 0  ] , [ 0, 255 , 0 ] ,[ 0, 255 , 0 ]]])

plt.imshow(arr)

"""# CREATING GREEN IMAGE"""

arr = np.array([[[ 0,0, 255 ] , [ 0,0, 255 ] ,[ 0,0, 255 ]],
                [[ 0,0, 255 ] , [ 0,0, 255 ] ,[ 0,0, 255 ]],
                [[ 0,0, 255 ] , [ 0,0, 255 ] ,[ 0,0, 255 ]]])

plt.imshow(arr)



"""# Creating Red Green Blue Image Pattern"""

arr = np.array([[[ 255,0,0 ] , [ 255,0,0 ] ,[ 255,0,0 ]],
                [[ 0,255,0 ] , [ 0,255,0 ] ,[ 0,255,0 ]],
                [[ 0,0,255 ] , [ 0,0,255 ] ,[ 0,0,255 ]]])

plt.imshow(arr)