# -*- coding: utf-8 -*-
"""How to make pixel transition in an Image.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18yEVMpTdEYbRgxDtAXgVn8sys7qvuK3D
"""

import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt



"""# 1. Creating Different Shared of Red

"""

arr = np.array([[[ 30  , 0 , 0 ] , [ 60  , 0 , 0 ] ,[ 90  , 0 , 0 ]],
                [[ 120 , 0 , 0 ] , [ 150 , 0 , 0 ] ,[ 180 , 0 , 0 ]],
                [[ 210 , 0 , 0 ] , [ 240 , 0 , 0 ] ,[ 255 , 0 , 0 ]]])

plt.imshow(arr)



"""# 2. Creating Different Shades of Green"""

arr = np.array([[[ 0, 30  , 0  ] , [ 0, 60  , 0 ] ,[ 0, 90  , 0 ]],
                [[ 0, 120 , 0  ] , [ 0, 150 , 0 ] ,[ 0, 180 , 0 ]],
                [[ 0, 210 , 0  ] , [ 0, 240 , 0 ] ,[ 0, 255 , 0 ]]])

plt.imshow(arr)

"""#  Creating DIfferent Shades of Blue"""

arr = np.array([[[ 0,0, 30  ] , [ 0,0, 60  ] ,[ 0,0, 90  ]],
                [[ 0,0, 120 ] , [ 0,0, 150 ] ,[ 0,0, 180 ]],
                [[ 0,0, 210 ] , [ 0,0, 240 ] ,[ 0,0, 255 ]]])

plt.imshow(arr)



""" Merging all the Images given above"""

arr=np.array([[[ 0   , 70 , 0  ] , [ 0   ,150, 0 ] ,[ 0   ,255,  0 ]],
              [[ 70  , 0  , 0  ] , [ 150 , 0 , 0 ] ,[ 255 , 0 ,  0 ]],
              [[ 0   , 0  , 70 ] , [ 0   , 0 ,150] ,[ 0   , 0 , 255]]])

plt.imshow(arr)

"""# Creating Shades of Red - Dense"""

img=[]
for i in range(256):
  t=[]
  for j in range(256):
    t.append([i,0,0])
  img.append(t)
img=np.array(img)
plt.imshow(img)



"""#  Creating Shades of Green - Dense"""

img=[]
for i in range(256):
  t=[]
  for j in range(256):
    t.append([0,i,0])
  img.append(t)
img=np.array(img)
plt.imshow(img)



"""# Creating Shades of blue - Dense"""

img=[]
for i in range(256):
  t=[]
  for j in range(256):
    t.append([0,0,i])
  img.append(t)
img=np.array(img)
plt.imshow(img)



"""# Merging these three shades"""

img = []

# Red

for i in range(256):             # from Black to Red
    t = []
    for j in range(1536):
        t.append([i,0,0])
    img.append(t)

for i in range(256,0,-1):        # from Red to Black
    t = []
    for j in range(1536):
        t.append([i,0,0])
    img.append(t)

# Green

for i in range(256):             # from Black to Green
    t = []
    for j in range(1536):
        t.append([0,i,0])
    img.append(t)


for i in range(256,0,-1):        # from Green to Black
    t = []
    for j in range(1536):
        t.append([0,i,0])
    img.append(t)



#Blue


for i in range(256):             # from Black to Blue
    t = []
    for j in range(1536):
        t.append([0,0,i])
    img.append(t)

for i in range(256,0,-1):        # from Blue to Black
    t = []
    for j in range(1536):
        t.append([0,0,i])
    img.append(t)






img = np.array(img)

plt.imshow(img)

