# -*- coding: utf-8 -*-
"""What is RGB Colour scale?.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WaN9anrGOwiOKCSSqH0-DMB0zW9rDCgV
"""

import cv2 as cv

import numpy as np

import matplotlib.pyplot as plt

arr = np.array([[ 255 , 0 , 255,0 ] ,
 [ 0 , 255 , 0,255 ] ,
                   [  255, 0,   255, 0],
  [ 0 , 255 , 0 ,255]
                ])

arr

plt.imshow(arr)

"""RGB
BGR


R- RED
G- GREEN

B-BLUE


BLACK=0,0,0
WHITE=255,255,255
"""

arr = np.array([[ 255 , 0 , 255 ] ,
 [ 0 , 255 , 0 ] ,

  [ 255 , 0 , 255 ]
                ])

plt.imshow(arr)



"""### **CREATING RGB IMAGE**

"""

arr = np.array([[[ 0 , 0 , 0 ] , [ 255 , 255 , 255 ] ,[ 0 , 0 , 0 ]],
                [[ 255, 255 , 255 ] , [ 0 , 0 , 0 ] ,[ 255 , 255 , 255 ]],
                [[ 0 , 0 , 0 ] , [ 255 , 255, 255 ] ,[ 0 , 0 , 0 ]]])

plt.imshow(arr)

cv.imwrite('Black_WHITE.png',arr)

"""# BLACK IMAGE"""

arr = np.array([[[ 0 , 0 , 0 ] , [ 0 , 0 , 0 ] ,[ 0 , 0 , 0 ]],
                [[ 0 , 0 , 0 ] , [ 0 , 0 , 0 ] ,[ 0 , 0 , 0 ]],
                [[ 0 , 0 , 0 ] , [ 0 , 0 , 0 ] ,[ 0 , 0 , 0 ]]])


plt.imshow(arr)

cv.imwrite('Black.png',arr)

"""## White image"""

arr = np.array([[[255,255,255] , [255,255,255] ,[255,255,255]],
                [[255,255,255] , [255,255,255] ,[255,255,255]],
                [[255,255,255] , [255,255,255] ,[255,255,255]]])

plt.imshow(arr)

cv.imwrite('White.png',arr)

"""
3. Creating Pattern in Black and White with RGB Colour **Space**"""

arr = np.array([[[ 0 , 0 , 0 ] , [255,255,255] ,[ 0 , 0 , 0 ]],
                [[255,255,255] , [ 0 , 0 , 0 ] ,[255,255,255]],
                [[ 0 , 0 , 0 ] , [255,255,255] ,[0 , 0 , 0 ]]])

plt.imshow(arr)

cv.imwrite('pattern_RGB.png',arr)



"""## Creating Pattern Image with Gray Colour **Space**"""

arr = np.array([[0  ,255, 0],
                [255, 0 ,255],
                [0  ,255, 0]])

plt.imshow(arr)

cv.imwrite('pattern_Gray.png',arr)